[Lancet-2]
tags = [ "远程位", "治疗", "支援机械", "医疗干员",]
star = 1

[Castle-3]
tags = [ "近战位", "支援", "支援机械", "近卫干员",]
star = 1

[THRM-EX]
tags = [ "近战位", "爆发", "支援机械", "特种干员",]
star = 1

["正义骑士号"]
tags = [ "远程位", "支援", "支援机械", "狙击干员",]
star = 1

[12F]
tags = [ "远程位", "新手", "术师干员",]
star = 2

["杜林"]
tags = [ "远程位", "新手", "术师干员",]
star = 2

["巡林者"]
tags = [ "远程位", "新手", "狙击干员",]
star = 2

["黑角"]
tags = [ "近战位", "新手", "重装干员",]
star = 2

["夜刀"]
tags = [ "近战位", "新手", "近卫干员",]
star = 2

["安德切尔"]
tags = [ "远程位", "输出", "狙击干员",]
star = 3

["芬"]
tags = [ "近战位", "费用回复", "先锋干员",]
star = 3

["香草"]
tags = [ "近战位", "费用回复", "先锋干员",]
star = 3

["翎羽"]
tags = [ "近战位", "输出", "费用回复", "先锋干员",]
star = 3

["玫兰莎"]
tags = [ "近战位", "输出", "生存", "近卫干员",]
star = 3

["米格鲁"]
tags = [ "近战位", "防护", "重装干员",]
star = 3

["克洛丝"]
tags = [ "远程位", "输出", "狙击干员",]
star = 3

["炎熔"]
tags = [ "远程位", "群攻", "术师干员",]
star = 3

["芙蓉"]
tags = [ "远程位", "治疗", "医疗干员",]
star = 3

["安赛尔"]
tags = [ "远程位", "治疗", "医疗干员",]
star = 3

["史都华德"]
tags = [ "远程位", "输出", "术师干员",]
star = 3

["梓兰"]
tags = [ "远程位", "减速", "辅助干员",]
star = 3

["空爆"]
tags = [ "远程位", "群攻", "狙击干员",]
star = 3

["月见夜"]
tags = [ "近战位", "输出", "近卫干员",]
star = 3

["泡普卡"]
tags = [ "近战位", "群攻", "生存", "近卫干员",]
star = 3

["斑点"]
tags = [ "近战位", "防护", "治疗", "重装干员",]
star = 3

["夜烟"]
tags = [ "远程位", "输出", "削弱", "术师干员",]
star = 4

["远山"]
tags = [ "远程位", "群攻", "术师干员",]
star = 4

["杰西卡"]
tags = [ "远程位", "输出", "生存", "狙击干员",]
star = 4

["流星"]
tags = [ "远程位", "输出", "削弱", "狙击干员",]
star = 4

["白雪"]
tags = [ "远程位", "群攻", "减速", "狙击干员",]
star = 4

["清道夫"]
tags = [ "近战位", "费用回复", "输出", "先锋干员",]
star = 4

["红豆"]
tags = [ "近战位", "输出", "费用回复", "先锋干员",]
star = 4

["杜宾"]
tags = [ "近战位", "输出", "支援", "近卫干员",]
star = 4

["缠丸"]
tags = [ "近战位", "生存", "输出", "近卫干员",]
star = 4

["霜叶"]
tags = [ "近战位", "减速", "输出", "近卫干员",]
star = 4

["艾丝黛尔"]
tags = [ "近战位", "群攻", "生存", "近卫干员",]
star = 4

["慕斯"]
tags = [ "近战位", "输出", "近卫干员",]
star = 4

["砾"]
tags = [ "近战位", "快速复活", "防护", "特种干员",]
star = 4

["暗索"]
tags = [ "近战位", "位移", "特种干员",]
star = 4

["末药"]
tags = [ "远程位", "治疗", "医疗干员",]
star = 4

["调香师"]
tags = [ "远程位", "治疗", "医疗干员",]
star = 4

["角峰"]
tags = [ "近战位", "防护", "重装干员",]
star = 4

["蛇屠箱"]
tags = [ "近战位", "防护", "重装干员",]
star = 4

["古米"]
tags = [ "近战位", "防护", "治疗", "重装干员",]
star = 4

["地灵"]
tags = [ "远程位", "减速", "辅助干员",]
star = 4

["阿消"]
tags = [ "近战位", "位移", "特种干员",]
star = 4

["猎蜂"]
tags = [ "近战位", "输出", "近卫干员",]
star = 4

["格雷伊"]
tags = [ "远程位", "群攻", "减速", "术师干员",]
star = 4

["苏苏洛"]
tags = [ "远程位", "治疗", "医疗干员",]
star = 4

["桃金娘"]
tags = [ "近战位", "费用回复", "治疗", "先锋干员",]
star = 4

["红云"]
tags = [ "远程位", "输出", "狙击干员",]
star = 4

["梅"]
tags = [ "远程位", "输出", "减速", "狙击干员",]
star = 4

["安比尔"]
tags = [ "远程位", "输出", "减速", "狙击干员",]
star = 4

["清流"]
tags = [ "远程位", "治疗", "支援", "医疗干员",]
star = 4

["宴"]
tags = [ "近战位", "输出", "生存", "近卫干员",]
star = 4

["德克萨斯"]
tags = [ "近战位", "费用回复", "控场", "资深干员", "先锋干员",]
star = 5

["凛冬"]
tags = [ "近战位", "费用回复", "支援", "资深干员", "先锋干员",]
star = 5

["苇草"]
tags = [ "近战位", "费用回复", "输出", "资深干员", "先锋干员",]
star = 5

["布洛卡"]
tags = [ "近战位", "群攻", "生存", "资深干员", "近卫干员",]
star = 5

["诗怀雅"]
tags = [ "近战位", "输出", "支援", "资深干员", "近卫干员",]
star = 5

["星极"]
tags = [ "近战位", "输出", "防护", "资深干员", "近卫干员",]
star = 5

["因陀罗"]
tags = [ "近战位", "输出", "生存", "资深干员", "近卫干员",]
star = 5

["幽灵鲨"]
tags = [ "近战位", "群攻", "生存", "资深干员", "近卫干员",]
star = 5

["白金"]
tags = [ "远程位", "输出", "资深干员", "狙击干员",]
star = 5

["灰喉"]
tags = [ "远程位", "输出", "资深干员", "狙击干员",]
star = 5

["蓝毒"]
tags = [ "远程位", "输出", "资深干员", "狙击干员",]
star = 5

["普罗旺斯"]
tags = [ "远程位", "输出", "资深干员", "狙击干员",]
star = 5

["慑砂"]
tags = [ "远程位", "群攻", "削弱", "资深干员", "狙击干员",]
star = 5

["守林人"]
tags = [ "远程位", "输出", "爆发", "资深干员", "狙击干员",]
star = 5

["送葬人"]
tags = [ "远程位", "群攻", "资深干员", "狙击干员",]
star = 5

["陨星"]
tags = [ "远程位", "群攻", "削弱", "资深干员", "狙击干员",]
star = 5

["吽"]
tags = [ "近战位", "防护", "治疗", "资深干员", "重装干员",]
star = 5

["火神"]
tags = [ "近战位", "生存", "防护", "输出", "资深干员", "重装干员",]
star = 5

["可颂"]
tags = [ "近战位", "防护", "位移", "资深干员", "重装干员",]
star = 5

["雷蛇"]
tags = [ "近战位", "防护", "输出", "资深干员", "重装干员",]
star = 5

["临光"]
tags = [ "近战位", "防护", "治疗", "资深干员", "重装干员",]
star = 5

["白面鸮"]
tags = [ "远程位", "治疗", "支援", "资深干员", "医疗干员",]
star = 5

["赫默"]
tags = [ "远程位", "治疗", "资深干员", "医疗干员",]
star = 5

["华法琳"]
tags = [ "远程位", "治疗", "支援", "资深干员", "医疗干员",]
star = 5

["初雪"]
tags = [ "远程位", "削弱", "资深干员", "辅助干员",]
star = 5

["格劳克斯"]
tags = [ "远程位", "减速", "控场", "资深干员", "辅助干员",]
star = 5

["梅尔"]
tags = [ "远程位", "召唤", "控场", "资深干员", "辅助干员",]
star = 5

["真理"]
tags = [ "远程位", "减速", "输出", "资深干员", "辅助干员",]
star = 5

["惊蛰"]
tags = [ "远程位", "输出", "资深干员", "术师干员",]
star = 5

["夜魔"]
tags = [ "远程位", "输出", "治疗", "减速", "资深干员", "术师干员",]
star = 5

["红"]
tags = [ "近战位", "快速复活", "控场", "资深干员", "特种干员",]
star = 5

["槐琥"]
tags = [ "近战位", "快速复活", "削弱", "资深干员", "特种干员",]
star = 5

["狮蝎"]
tags = [ "近战位", "输出", "生存", "资深干员", "特种干员",]
star = 5

["食铁兽"]
tags = [ "近战位", "位移", "减速", "资深干员", "特种干员",]
star = 5

["崖心"]
tags = [ "近战位", "位移", "输出", "资深干员", "特种干员",]
star = 5

["风笛"]
tags = [ "近战位", "费用回复", "输出", "高级资深干员", "先锋干员",]
star = 6

["推进之王"]
tags = [ "近战位", "费用回复", "输出", "高级资深干员", "先锋干员",]
star = 6

["陈"]
tags = [ "近战位", "爆发", "输出", "高级资深干员", "近卫干员",]
star = 6

["赫拉格"]
tags = [ "近战位", "输出", "生存", "高级资深干员", "近卫干员",]
star = 6

["煌"]
tags = [ "近战位", "输出", "生存", "高级资深干员", "近卫干员",]
star = 6

["斯卡蒂"]
tags = [ "近战位", "输出", "生存", "高级资深干员", "近卫干员",]
star = 6

["银灰"]
tags = [ "近战位", "输出", "支援", "高级资深干员", "近卫干员",]
star = 6

["黑"]
tags = [ "远程位", "输出", "高级资深干员", "狙击干员",]
star = 6

["能天使"]
tags = [ "远程位", "输出", "高级资深干员", "狙击干员",]
star = 6

["塞雷娅"]
tags = [ "近战位", "防护", "治疗", "支援", "高级资深干员", "重装干员",]
star = 6

["星熊"]
tags = [ "近战位", "防护", "输出", "高级资深干员", "重装干员",]
star = 6

["闪灵"]
tags = [ "远程位", "治疗", "支援", "高级资深干员", "医疗干员",]
star = 6

["夜莺"]
tags = [ "远程位", "治疗", "支援", "高级资深干员", "医疗干员",]
star = 6

["麦哲伦"]
tags = [ "远程位", "支援", "减速", "输出", "高级资深干员", "辅助干员",]
star = 6

["刻俄柏"]
tags = [ "远程位", "输出", "控场", "高级资深干员", "术师干员",]
star = 6

["莫斯提马"]
tags = [ "远程位", "群攻", "支援", "控场", "高级资深干员", "术师干员",]
star = 6

["伊芙利特"]
tags = [ "远程位", "群攻", "削弱", "高级资深干员", "术师干员",]
star = 6

["阿"]
tags = [ "远程位", "支援", "输出", "高级资深干员", "特种干员",]
star = 6
